# frozen_string_literal: true

module Jekyll
module Plugins
module PaginateV3
module Pagination
	class Paginator < ::Liquid::Drop
		# Exposes pagination metadata to Liquid as `paginator`.
		#
		# Implemented as a Liquid Drop so paginator keys can be lazy methods
		# while still supporting legacy key aliases.
		#
		# Used by Pagination::Model for every generated page/document.
		
		# Builds one paginator instance for one generated index page.
		#
		# `compatibility` controls whether legacy v1/v2 keys are also emitted
		# in the Liquid payload.
		#
		# `page_windows` can be supplied by the model to avoid recomputing
		# variable per-page index windows for every paginator instance.
		
		attr_reader :per_page, :items, :total_items, :total_indexes,
		            :current, :next, :prev, :first, :last, :trail, :groups

		def initialize(per_page:, items:, current_page:, total_pages:, item_keyword:, compatibility: nil, page_windows: nil)
			@per_page_pattern = Utils.normalise_per_page_pattern(per_page)
			@current_index_number = current_page.to_i
			@item_keyword = normalise_item_keyword(item_keyword)
			@compatibility_mode = normalise_compatibility_mode(compatibility)
			@total_items = items.size
			@page_windows = normalise_page_windows(page_windows, @total_items)
			requested_total_indexes = [total_pages.to_i, 1].max

			if @current_index_number > requested_total_indexes
				raise ArgumentError, "page number cannot be greater than total pages (#{@current_index_number} > #{requested_total_indexes})"
			end

			if requested_total_indexes != @page_windows.length
				raise ArgumentError, "total pages does not match page windows (#{requested_total_indexes} != #{@page_windows.length})"
			end
			@total_indexes = requested_total_indexes

			current_window = window_for_page_number(@current_index_number)
			@per_page = current_window['page_size']
			@items = items[current_window['offset_start']...current_window['offset_end']] || []
			@trail = nil
			@groups = []

			@current_page_object = nil

			initialise_index_references!
		end

		# Attaches actual generated page/document objects to neighbour links.
		#
		# We intentionally keep `current.page` unset so templates can detect
		# the current index without comparing object identities.
		def bind_pages(current_page_object:, previous_page_object:, next_page_object:, first_page_object:, last_page_object:)
			@current_page_object = current_page_object
			@current = build_index_reference(@current_index_number, nil)
			@prev = @current_index_number > 1 ? build_index_reference(@current_index_number - 1, previous_page_object) : nil
			@next = @current_index_number < @total_indexes ? build_index_reference(@current_index_number + 1, next_page_object) : nil
			@first = build_index_reference(1, first_page_object, allow_current_page_object: true)
			@last = build_index_reference(@total_indexes, last_page_object, allow_current_page_object: true)
		end

		# Assigns trail entries generated by the pagination model.
		def trail=(trail_entries)
			@trail = trail_entries
		end

		# Assigns grouped-set navigation metadata (`paginator.groups`).
		def groups=(group_payloads)
			@groups = Utils.arrayify(group_payloads).compact
		end

		# Shortcut to the deepest grouped-set payload.
		def group
			groups.last
		end

		# Builds one trail entry for a page number.
		#
		# Used by the model so trail windows can reuse canonical index maths.
		def build_trail_reference(page_number:, page_object:, current:, distance:)
			window = window_for_page_number(page_number)

			TrailReference.new(
				num: page_number,
				page_object: page_object,
				item_count: window['count'],
				start_item_index: window['start'],
				end_item_index: window['end'],
				current: current,
				distance: distance
			)
		end

		# Legacy v1/v2 alias for current page number.
		def page
			return nil unless compatibility_mode?

			current&.num
		end

		# Legacy v1/v2 alias for total page count.
		def total_pages
			return nil unless compatibility_mode?

			total_indexes
		end

		# Legacy v1/v2 alias for current page URL.
		def page_path
			return nil unless compatibility_mode?

			index_reference_path(current)
		end

		# Legacy v1/v2 alias for previous page number.
		def previous_page
			return nil unless compatibility_mode?

			prev&.num
		end

		# Legacy v1/v2 alias for previous page URL.
		def previous_page_path
			return nil unless compatibility_mode?

			index_reference_path(prev)
		end

		# Legacy v1/v2 alias for next page number.
		def next_page
			return nil unless compatibility_mode?

			self.next&.num
		end

		# Legacy v1/v2 alias for next page URL.
		def next_page_path
			return nil unless compatibility_mode?

			index_reference_path(self.next)
		end

		# Legacy v1/v2 alias for first page number.
		def first_page
			return nil unless compatibility_mode?

			first&.num
		end

		# Legacy v1/v2 alias for first page URL.
		def first_page_path
			return nil unless compatibility_mode?

			index_reference_path(first)
		end

		# Legacy v1/v2 alias for last page number.
		def last_page
			return nil unless compatibility_mode?

			last&.num
		end

		# Legacy v1/v2 alias for last page URL.
		def last_page_path
			return nil unless compatibility_mode?

			index_reference_path(last)
		end

		# Legacy v1/v2 alias for trail payload shape.
		def page_trail
			return nil unless compatibility_mode?

			compatibility_page_trail
		end

		# Hash form used by specs and non-Liquid inspection.
		#
		# Liquid rendering uses this Drop instance directly.
		def to_h
			payload = canonical_payload_hash
			payload[@item_keyword] = items
			payload["total_#{@item_keyword}"] = total_items

			if compatibility_mode?
				payload.merge!(
					'per_page' => per_page,
					'page' => page,
					'total_pages' => total_pages,
					'page_path' => page_path,
					'previous_page' => previous_page,
					'previous_page_path' => previous_page_path,
					'next_page' => next_page,
					'next_page_path' => next_page_path,
					'first_page' => first_page,
					'first_page_path' => first_page_path,
					'last_page' => last_page,
					'last_page_path' => last_page_path,
					'page_trail' => page_trail
				)
			end

			payload
		end

		# Handles dynamic alias keys that are not explicit methods.
		def liquid_method_missing(method_name)
			method_key = method_name.to_s
			return items if method_key == @item_keyword
			return total_items if method_key == "total_#{@item_keyword}"

			super
		end

		private

		# Canonical v3 paginator payload hash.
		def canonical_payload_hash
			{
				'items' => items,
				'total_items' => total_items,
				'total_indexes' => total_indexes,
				'current' => current,
				'next' => self.next,
				'prev' => prev,
				'first' => first,
				'last' => last,
				'trail' => trail || [],
				'groups' => groups,
				'group' => group
			}
		end

		# Initialises numeric index references before page objects are bound.
		def initialise_index_references!
			@current = build_index_reference(@current_index_number, nil)
			@prev = @current_index_number > 1 ? build_index_reference(@current_index_number - 1, nil) : nil
			@next = @current_index_number < @total_indexes ? build_index_reference(@current_index_number + 1, nil) : nil
			@first = build_index_reference(1, nil)
			@last = build_index_reference(@total_indexes, nil)
		end

		# Builds one index reference, leaving `page` unset for current index.
		def build_index_reference(page_number, page_object, allow_current_page_object: false)
			is_current_page = page_number == @current_index_number
			page_reference = if is_current_page && !allow_current_page_object
													nil
												else
													page_object
												end
			window = window_for_page_number(page_number)

			IndexReference.new(
				num: page_number,
				page_object: page_reference,
				item_count: window['count'],
				start_item_index: window['start'],
				end_item_index: window['end']
			)
		end

		# Returns window metadata for one index page.
		def window_for_page_number(page_number)
			@page_windows_by_number.fetch(page_number.to_i)
		rescue KeyError
			fallback_size = Utils.page_size_for_number(@per_page_pattern, page_number)
			{
				'num' => page_number.to_i,
				'page_size' => fallback_size,
				'count' => 0,
				'offset_start' => total_items,
				'offset_end' => total_items,
				'start' => nil,
				'end' => nil
			}
		end

		# Normalises page-window metadata for this pagination set.
		def normalise_page_windows(raw_page_windows, total_item_count)
			raw_windows = if raw_page_windows.is_a?(Array) && !raw_page_windows.empty?
											raw_page_windows
										else
											Utils.build_pagination_windows(total_item_count, @per_page_pattern)
										end

			windows = raw_windows.map { |entry| Utils.safe_hash(entry) }.sort_by { |entry| entry['num'].to_i }
			windows = Utils.build_pagination_windows(total_item_count, @per_page_pattern) if windows.empty?

			@page_windows_by_number = {}
			windows.each do |window|
				window_number = window['num'].to_i
				@page_windows_by_number[window_number] = {
					'num' => window_number,
					'page_size' => [window['page_size'].to_i, 1].max,
					'count' => [window['count'].to_i, 0].max,
					'offset_start' => [window['offset_start'].to_i, 0].max,
					'offset_end' => [window['offset_end'].to_i, 0].max,
					'start' => window['start'],
					'end' => window['end']
				}
			end

			@page_windows_by_number.values
		end

		# Normalises item alias keyword; falls back to canonical `items`.
		def normalise_item_keyword(raw_keyword)
			keyword = raw_keyword.to_s.strip
			keyword.empty? ? 'items' : keyword
		end

		# Normalises compatibility mode to one supported legacy profile.
		def normalise_compatibility_mode(raw_mode)
			mode = raw_mode.to_s.strip.downcase
			return nil unless %w[v1 v2].include?(mode)

			mode
		end

		# Indicates whether legacy payload projection is enabled.
		def compatibility_mode?
			!@compatibility_mode.nil?
		end

		# Maps v3 trail references to legacy `page_trail` entries.
		def compatibility_page_trail
			return nil if trail.nil?

			trail.map do |entry|
				page_object = page_object_for_trail_entry(entry)
				{
					'num' => entry.num,
					'path' => page_object_url(page_object),
					'title' => page_object_title(page_object)
				}
			end
		end

		# Resolves the concrete page object represented by an index reference.
		def page_object_for_index_reference(index_reference)
			return nil if index_reference.nil?
			return @current_page_object if index_reference.num == current.num

			index_reference.page
		end

		# Resolves the concrete page object represented by one trail entry.
		def page_object_for_trail_entry(trail_entry)
			return @current_page_object if trail_entry.current

			page_object_for_index_reference(trail_entry)
		end

		# Returns one canonical URL for the supplied index reference.
		def index_reference_path(index_reference)
			page_object_url(page_object_for_index_reference(index_reference))
		end

		# Reads canonical route URL from a page/document object.
		def page_object_url(page_object)
			return nil if page_object.nil?
			return nil unless page_object.respond_to?(:url)

			url = page_object.url.to_s
			return nil if url.strip.empty?

			Utils.ensure_leading_slash(url)
		end

		# Reads page/document title for legacy trail entries.
		def page_object_title(page_object)
			return nil if page_object.nil?
			return nil unless page_object.respond_to?(:data)

			title = Utils.safe_hash(page_object.data)['title'].to_s
			return nil if title.strip.empty?

			title
		end
	end

	# Lightweight Liquid-facing object for paginator neighbour links.
	#
	# Exposed under `paginator.current`, `paginator.next`, `paginator.prev`,
	# `paginator.first`, and `paginator.last`.
	class IndexReference < ::Liquid::Drop
		attr_reader :num, :page

		# Stores one page number plus optional page/document object and
		# positional metadata within the full paginated set.
		def initialize(num:, page_object:, item_count:, start_item_index:, end_item_index:)
			@num = num.to_i
			@page = page_object
			@item_count = item_count.to_i
			@start_item_index = start_item_index
			@end_item_index = end_item_index
		end

		# Number of items paginated to this index.
		def count
			@item_count
		end

		# 1-based index of the first item on this index.
		def start
			@start_item_index
		end

		# Hash form used by specs and non-Liquid inspection.
		def to_h
			{
				'num' => num,
				'page' => page,
				'count' => count,
				'start' => start,
				'end' => @end_item_index
			}
		end

		# Handles `end` because it is a Ruby keyword and cannot be a method name.
		def liquid_method_missing(method_name)
			return @end_item_index if method_name.to_s == 'end'

			super
		end
	end

	# Liquid-facing trail object used by `paginator.trail`.
	#
	# Extends IndexReference with current-page markers and relative distance.
	class TrailReference < IndexReference
		attr_reader :current, :distance

		# Stores trail metadata for one visible trail index entry.
		def initialize(num:, page_object:, item_count:, start_item_index:, end_item_index:, current:, distance:)
			super(
				num: num,
				page_object: page_object,
				item_count: item_count,
				start_item_index: start_item_index,
				end_item_index: end_item_index
			)
			@current = !!current
			@distance = distance.to_i
		end

		# Hash form used by specs and non-Liquid inspection.
		def to_h
			super.merge(
				'current' => current,
				'distance' => distance
			)
		end
	end

	# Liquid-facing grouped-set payload for generated grouped indexes.
	#
	# Exposed in `paginator.groups` and by shortcut at `paginator.group`
	# (deepest index level).
	class GroupPayload < ::Liquid::Drop
		attr_reader :key, :current, :next, :prev, :first, :last

		# Stores one complete set of group neighbour references.
		def initialize(key:, current:, next_reference:, prev_reference:, first_reference:, last_reference:)
			@key = key.to_s
			@current = current
			@next = next_reference
			@prev = prev_reference
			@first = first_reference
			@last = last_reference
		end

		# Hash form used by specs and non-Liquid inspection.
		def to_h
			{
				'key' => key,
				'current' => current,
				'next' => self.next,
				'prev' => prev,
				'first' => first,
				'last' => last
			}
		end
	end

	# Liquid-facing grouped-set reference.
	#
	# Similar to IndexReference, but `start`/`end` represent group range
	# bounds rather than 1-based item positions.
	class GroupReference < ::Liquid::Drop
		attr_reader :num, :page, :count, :start

		# Stores one grouped-set neighbour reference.
		def initialize(num:, page_object:, item_count:, range_start:, range_end:)
			@num = num.to_i
			@page = page_object
			@count = item_count.to_i
			@start = range_start
			@range_end = range_end
		end

		# Hash form used by specs and non-Liquid inspection.
		def to_h
			payload = {
				'num' => num,
				'page' => page,
				'count' => count,
				'start' => start
			}
			payload['end'] = @range_end unless @range_end.nil?
			payload
		end

		# Handles `end` because it is a Ruby keyword and cannot be a method name.
		def liquid_method_missing(method_name)
			return @range_end if method_name.to_s == 'end'

			super
		end
	end

	# Backwards-compatible aliases so grouped payload classes remain
	# reachable under `Paginator::...` as expected by callers.
	class Paginator
		GroupPayload = Pagination::GroupPayload unless const_defined?(:GroupPayload, false)
		GroupReference = Pagination::GroupReference unless const_defined?(:GroupReference, false)
	end
end
end
end
end
